### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by Plailect**
Enjoy!

### CODE REVIEW

**Comment by mariogamer2** [comment]
You should take a break...

Heuuuu Am I talking to a bot? xd

**Comment by mariogamer2** [comment]
No definitely talking to a bot :P.

**Comment by rashevskyv** [comment]
How can I add already translated files?

**Comment by THEDARKK** [comment]
@rashevskyv http://translate.3ds.guide/

**Comment by rashevskyv** [comment]
@THEDARKK Can I add somehow already working and tested md files?

**Pull request closed without merging**
