### PR TITLE
First translation to Brazilian Portuguese

### PR DESCRIPTION
**Pull request by s1cp**
All the steps from start to finish are manually translated from English to Brazilian Portuguese. All that is left are some extra pages like region changing, troubleshooting, nand size, updating a9lh, etc.

### CODE REVIEW

**Comment by jkcgs** [comment]
We are not translating with Github (at least by now). @Plailect is setting up Crowdin so we can do that. Please come to our discord server to coordinate translation. https://discord.gg/eP5Q9

**Comment by s1cp** [comment]
Thanks for the heads up, I'm now translating it at Crowdin.
Also, the invite link you provided isn't working.

**Comment by kevinchau321** [comment]
I'm really glad to see the crowdin effort gaining some momentum. Seems like a good platform for crowd sourcing all the current translations!

**Comment by jkcgs** [comment]
Sorry @s1cp this one should work https://discord.gg/HPgJzjM
Also, Plailect said that we should wait him to setup Crowdin correctly

**Comment by jkcgs** [comment]
@kevinchau321 It's also used by the dolphin-emu team

**Pull request closed without merging**
