### PR TITLE
Mention the translations on the US Home Page

### PR DESCRIPTION
**Pull request by ItsKipz**

### CODE REVIEW

**Comment by Plailect** [comment]
Repeating the subject like that isn't really proper English...

**Comment by ItsKipz** [comment]
Shouldn't there be something about the translations? Most people don't even know the guide is being translated right now.

**Comment by Plailect** [comment]
I added it manually, but my point is that the sentence you were suggesting didn't make sense.

**Comment by ItsKipz** [comment]
Oh great, my bad. This was a quick thing i wanted to put in after looking at translate.3ds.guide.

**Pull request closed without merging**
