### PR TITLE
Update DSiWare-List.md

### PR DESCRIPTION
**Pull request by einstein95**
Just the DSiWare I had on hand, not the ones that matched the size exactly though, just those that were larger than 3,457,024 bytes and a public.sav greater than or equal to 81,920 bytes as per the header.

### CODE REVIEW

**Comment by Plailect** [comment]
Prices would be helpful, but I could also add them myself if you can't do it by later today.

**Comment by idgrepthat** [comment]
Seems like there is wrong titles on the list. G.G. series games are usually 16kb saves for instance like the spiky blowfish one.

**Comment by einstein95** [comment]
@Plailect: yeah, feel free to add prices.
@Idgrepthat: the public.sav sizes are taken from the dsiware header. If you
get a save file that's smaller than sudoku's then please do tell me

**Comment by Plailect** [comment]
https://github.com/Plailect/Guide/commit/4c7fc519ac1a4e9379ffaec7204200c711552021

`savedata.bin` is found by mounting the `public.sav` file (which is fat12)

**Comment by Plailect** [comment]
Actually, I'll revert that commit. The size of the `public.sav` image just needs to be large enough to contain the `savedata.bin` of sudokuhax.

**Comment by akirayuki** [comment]
It seems like some games doesnt have savedata.bin. The one im trying right now has a folder named "save_data" and inside is a file named "system_flag.bin". So should i just rename the "savedata.bin" to system_flag.bin" and overwrite the one inside the "public.sav"?

**Comment by Plailect** [comment]
https://github.com/Plailect/Guide/commit/dbbaad4a8963d1b6116267285ff33ef8f14204ab

**Comment by Plailect** [comment]
@akirayuki not sure, what game?

**Comment by akirayuki** [comment]
@SIMPLE DS Vol.5 (a JPN game). The game fits the criteria, the only thing that is off is the one that I mentioned above. And also, I system transfered just to test it out but after it has been transferred to the target system, the game cannot be opened with this pop up ""This software cannot be launched. Please re-receive at Nintendo E-shop". I only translated it using google translate app

**Comment by idgrepthat** [comment]
> It seems like some games doesnt have savedata.bin. The one im trying right now has a folder named "save_data" and inside is a file named "system_flag.bin". So should i just rename the "savedata.bin" to system_flag.bin" and overwrite the one inside the "public.sav"?

NO. 
Use common sense. If you inject sudoku into a game, it will look for savedata.bin, not whatever the original game's files were called.

**Comment by FrozenChen** [comment]
@einstein95 Want to add some more info based on testing. 
>Chotto Dr. Mario (JP) cant be used for this, it's public.sav is only 16 KB 
Almost all @simple DS series (vol 2-3-4-5 tested) can be used for sudokuhax injection purposes, all the game have a ~10 mb .app and a 128kb public.sav, all attemps at the injection succeded

**Comment by Plailect** [comment]
https://github.com/Plailect/Guide/commit/b4716990e7a74f9ba376c71eb485cc3e61f93999

**Pull request closed without merging**
