### PR TITLE
Clarification on re-enabling wifi 

### PR DESCRIPTION
**Pull request by AnalogMan151**
Added extra clarification on how to re-enable wifi on 2DS and n3DS for people who are misunderstanding the troubleshooting step and leaving the AC charger plugged in.

### CODE REVIEW

**Comment by jkcgs** [comment]
The bug also affects to Old 3DS users? Because 2DS and New 3DS does not have the switch

**Comment by AnalogMan151** [comment]
Correct, this is not an issue on o3DS because it has a physical switch. This is clarification just for 2DS and n3DS.

**Comment by jkcgs** [comment]
Then the second commit is not valid, right?

**Comment by AnalogMan151** [comment]
I'm not sure what you're referring to. I put my reasoning in the commits description. Model of 3DS has nothing to do with it.

**Comment by jkcgs** [comment]
So my question is, do you actually need to remove the battery on Old 3DS while on 2.1.0 to turn on Wireless Communication?

**Comment by AnalogMan151** [comment]
No, you don't. But that page is not specific to the o3DS, it's used in downgrading all models and so it's useful to have there. Would you prefer if I changed it to this: "If your wifi switch is off and you have a 2DS or n3DS, unplug the 3DS and remove the battery for several seconds to enable wifi

**Comment by jkcgs** [comment]
With "If your wifi switch is off and you have a 2DS or n3DS", you are not talking about a physical switch? Because they don't have it.

**Comment by AnalogMan151** [comment]
Correct. Glad we could sort that out.

**Comment by jkcgs** [comment]
Great, thanks for this clarification of the clarification 😂

**Comment by AnalogMan151** [comment]
If it makes it clearer for you, the reference with the wifi switch is because that's the error message the 2DS or n3DS says on-screen while on system version 2.1. That's the exact wording it uses because 2.1 assumes you have a physical switch due to the 2DS and n3DS not being released at the time. So if you see the message about your wifi switch being off, then those are the steps you follow.

**Comment by jkcgs** [comment]
I got it now. Maybe you should clarify that you are refering to an error message, quoting it, or something like that.

**Pull request merged**
